VPN_SWITCH_RETRY_ATTEMPTS = 3
VPN_SWITCH_RETRY_BACKOFF = 2  # multiplier for the attempt number

VPN_THREAD_QUIT_RETRY_ATTEMPTS = 3
VPN_THREAD_QUIT_RETRY_BACKOFF = 2  # multiplier for the attempt number

VPN_MANAGE_CONNECTION_POLLING_SECONDS = 2
VPN_TRACK_CONNECTIONS_POLLING_SECONDS = 1
VPN_TRACK_PREFERENCES_POLLING_SECONDS = 1
VPN_TRACK_THREADS_POLLING_SECONDS = 1

VPN_SORT_NAMES = True

INTERNET_VERIFICATION_TIMEOUT = 2
